### ISSUE TITLE
Unable to recreate

### ISSUE THREAD

**Issue by bchampp** [appinho/SAStereoImage#1]
Hello!

I'm working on a similar project with stereo processing, and I have not been able to recreate your project. I don't see this header file included anywhere - #include "sensor_processing/DepthCompletionParamsConfig.h". 

Could you please let me know if you have it or if I am missing something?

Brent

**Comment by appinho** [comment]
I think if you „catkin_make“ these headers will be created.

**Comment by appinho** [comment]
Can you confirm it worked for you?

**Comment by bchampp** [comment]
Hi Simon, 

You are right that `catkin_make` created the headers, however they were built into `devel/include/` and were not exposed at compile time. I was able to finish the compilation by moving these header files out of devel into the src/include folder. I think this may be tied back to a difference in my C++ compiler, as I'm sure this may work fine with a different setup.
